Amplitude.init({
   songs: [
      {
         name: "Women's Health in Luganda - Introduction",
         url: './audio/001.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Overview",
         url: './audio/002.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - How To Get Rest",
         url: './audio/003.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Why You Should Get Regular Tests",
         url: './audio/004.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Reproductive Health Testing",
         url: './audio/005.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Importance Of Having Protected Sex",
         url: './audio/006.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - The Value Of Family Planning",
         url: './audio/007.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Maternal Health Before and After Birth",
         url: './audio/008.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Maternal Health (Uterus)",
         url: './audio/009.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Maternal Health (Frequent Urination)",
         url: './audio/010.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - How To Prevent Tetanus",
         url: './audio/011.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Why You Should Do Breast Checkups",
         url: './audio/012.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - How To Do Self Breast Examination",
         url: './audio/013.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - What To Do When You Find A Swelling",
         url: './audio/014.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - What You Need tO Know About Menstruation",
         url: './audio/015.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - Problems Encountered During Menstruation",
         url: './audio/016.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - What Cause Changes In Your Period",
         url: './audio/017.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - How To Reduce Menstrual Cramps",
         url: './audio/018.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - About Pre-Menstrual Symptoms",
         url: './audio/019.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - How To Prepare Yourself For Menstrual Symptoms",
         url: './audio/020.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - What To Do If You Lose A Lot Of Blood  Or Have A Long Menstrual Period",
         url: './audio/021.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - What To Do If You Lose Little Blood During Menstruation",
         url: './audio/022.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - What To Do If You Menstruate Too Often",
         url: './audio/023.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
      {
         name: "Women's Health in Luganda - What To Do If Your Period Stops Coming Or Takes Long To Come",
         url: './audio/024.mp3',
         source: 'Audiopedia',
         source_url: 'http://www.audiopedia.org',
      },
   ],
});